"""jobs.publication_id for kb_job_status correlation

Revision ID: 91cd4b8a59f2
Revises: da638beb045e
Create Date: 2026-09-19 18:54:00.591826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cd4b8a59f2'
down_revision: Union[str, Sequence[str], None] = 'da638beb045e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('publication_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_jobs_publication_id', 'jobs', 'publications', ['publication_id'], ['id']
    )
    # NOTE: autogenerate also proposed dropping 'ix_passages_embedding_hnsw'.
    # That index is real (see the previous migration) but created via raw SQL,
    # so it isn't in SQLAlchemy's metadata and autogenerate can't see it —
    # exactly the autogenerate blind spot references/data-and-db.md warns
    # about. Dropped from this migration; the index is untouched.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_publication_id', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'publication_id')
    # ### end Alembic commands ###
